### ISSUE TITLE
Move prod/dev env keys into policies

### ISSUE THREAD

**Issue by xbc5** [xbc5/hexo-csp#28]
This means:

```yaml
^path$:
  prod:
    directives: ...
  dev:
    directives: ...
```

Instead of:

```
yml
prod:
  ^path$:
    directives: ...
dev:
  ^path$:
    directives: ...
```

This avoids duplication of patterns. It still allows the user to apply patterns to one environment but not the other.
