### ISSUE TITLE
Support directives in frontmatter

### ISSUE THREAD

**Issue by xbc5** [xbc5/hexo-csp#5]
Support the same format as the URI syntax:

```yaml
csp
  mode: replace
  default-src: 'self'
  img-src: 'self'
```

Suppose merge mode by default.
